#!/usr/bin/env python3
"""
Generate pseudo-labels from the Ruinskiy & Lavner 2007 baseline.

WHY

Hand-labeling is slow. The Respiro-en (Interspeech 2024) recipe shows that
weak labels generated by a published baseline + a small set of hand labels
trains a strong neural detector. This script provides the "weak labels"
half: run Ruinskiy on a list of WAVs, write the predicted breath events as
.breath.json files that the training pipeline can consume.

These are NOT gold labels — Ruinskiy has known false-positive rate on
singing (it was designed for speech). Treat the output as silver labels
useful for augmenting a smaller hand-labeled set.

USAGE

    # Process a single WAV
    python generate_pseudo_labels.py path/to/audio.wav --out-dir /tmp/pseudo/

    # Process every WAV under a directory
    python generate_pseudo_labels.py path/to/excerpts/ --out-dir /tmp/pseudo/ --recursive

    # Adjust detector sensitivity (default threshold 0.5 from paper)
    python generate_pseudo_labels.py audio.wav --threshold 0.4 --out-dir /tmp/pseudo/
"""

from __future__ import annotations

import argparse
import json
import sys
import wave
from datetime import date
from pathlib import Path

from nanobreath.baseline.ruinskiy_lavner import RuinskiyDetector


def wav_duration_sec(wav_path: Path) -> float:
    with wave.open(str(wav_path), "rb") as wf:
        return wf.getnframes() / wf.getframerate()


def detect_and_save(wav_path: Path, out_dir: Path,
                    threshold: float = 0.5) -> tuple[Path, int]:
    """Run Ruinskiy on a WAV, write .breath.json into out_dir, return (path, n)."""
    detector = RuinskiyDetector(correlation_threshold=threshold)
    events = detector.detect_file(wav_path)

    out_dir.mkdir(parents=True, exist_ok=True)
    # Symlink the WAV so the training loader finds matching audio
    target_wav = out_dir / wav_path.name
    if not target_wav.exists():
        target_wav.symlink_to(wav_path.resolve())

    data = {
        "audio_file": wav_path.name,
        "sample_rate": 16000,
        "duration_sec": round(wav_duration_sec(wav_path), 4),
        "labeler": "ruinskiy_lavner_2007_pseudo",
        "label_date": date.today().isoformat(),
        "breath_events": [
            {
                "start_sec": round(e.start_sec, 4),
                "end_sec": round(e.end_sec, 4),
                "confidence": "low",  # weak / pseudo-labels
                "source": f"Ruinskiy & Lavner 2007 (correlation>={threshold})",
                "score": round(float(e.score), 4),
            }
            for e in events
        ],
        "notes": "PSEUDO-LABELS generated by Ruinskiy & Lavner 2007 baseline. "
                 "Use for training augmentation alongside hand labels.",
    }

    json_path = out_dir / wav_path.with_suffix(".breath.json").name
    json_path.write_text(json.dumps(data, indent=2))
    return json_path, len(events)


def main():
    p = argparse.ArgumentParser(description="Generate pseudo-labels from Ruinskiy baseline")
    p.add_argument("path", type=Path, help="WAV file or directory of WAVs")
    p.add_argument("--out-dir", type=Path, required=True)
    p.add_argument("--threshold", type=float, default=0.5,
                   help="Ruinskiy correlation threshold (default 0.5 from paper)")
    p.add_argument("--recursive", "-r", action="store_true")
    args = p.parse_args()

    if args.path.is_dir():
        if not args.recursive:
            p.error(f"{args.path} is a directory; pass --recursive to process all WAVs")
        wavs = sorted(args.path.rglob("*.wav"))
        if not wavs:
            print(f"No WAVs under {args.path}", file=sys.stderr)
            sys.exit(1)
        total_events = 0
        total_dur = 0.0
        for w in wavs:
            json_path, n = detect_and_save(w, args.out_dir, args.threshold)
            dur = wav_duration_sec(w)
            total_events += n
            total_dur += dur
            print(f"  ✓ {w.name}: {n:2d} events in {dur:5.1f}s "
                  f"({n / max(dur, 1e-6) * 60:4.1f}/min)")
        print(f"\nTotal: {total_events} pseudo-events in {total_dur:.1f}s "
              f"of audio ({total_events / max(total_dur, 1e-6) * 60:.1f}/min)")
    else:
        json_path, n = detect_and_save(args.path, args.out_dir, args.threshold)
        print(f"Wrote {json_path} ({n} pseudo events)")


if __name__ == "__main__":
    main()
