#!/usr/bin/env python3
"""Run the Ruinskiy & Lavner baseline over a directory of WAVs and write the
detected breath events as ``*.breath.json`` sidecars in the schema described in
``src/nanobreath/data/label_format.md``.

This produces a *pseudo-label* set we can train on while hand-labels are still
being collected — the Respiro-en self-training recipe.

The sidecar files are written next to the audio with ``confidence: "low"`` so
the training loss can down-weight them relative to hand labels (the dataset
loader applies a 0.5 weight to low-confidence frames automatically).

Usage::

    python scripts/generate_pseudo_labels.py \\
        --audio-root data/vocalset/FULL \\
        --out-dir   data/labels/pseudo \\
        --pattern   "*.wav" \\
        --limit     20            # cap for a quick smoke run
"""

from __future__ import annotations

import argparse
import json
from datetime import date
from pathlib import Path

from nanobreath.baseline.ruinskiy_lavner import RuinskiyDetector
from nanobreath.config import SAMPLE_RATE
from nanobreath.data.dataset import _read_wav_mono, _resample_audio  # type: ignore


def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="Generate pseudo-labels via Ruinskiy baseline")
    p.add_argument("--audio-root", type=Path, required=True,
                   help="root directory to scan for WAVs")
    p.add_argument("--out-dir", type=Path, required=True,
                   help="where to write pseudo-label sidecars (mirrors audio-root structure)")
    p.add_argument("--pattern", default="*.wav", help="glob pattern (default: *.wav)")
    p.add_argument("--threshold", type=float, default=0.5)
    p.add_argument("--limit", type=int, default=None,
                   help="stop after this many files (useful for a smoke run)")
    return p.parse_args()


def main() -> None:
    args = parse_args()
    args.out_dir.mkdir(parents=True, exist_ok=True)

    det = RuinskiyDetector(correlation_threshold=args.threshold)
    wavs = sorted(args.audio_root.rglob(args.pattern))
    if args.limit:
        wavs = wavs[:args.limit]
    if not wavs:
        raise SystemExit(f"No files matched {args.pattern!r} under {args.audio_root}")

    print(f"Scanning {len(wavs)} files...")
    n_events_total = 0
    for i, wav in enumerate(wavs, 1):
        signal, sr = _read_wav_mono(wav)
        if sr != SAMPLE_RATE:
            signal = _resample_audio(signal, sr, SAMPLE_RATE)
        events = det.detect_array(signal, SAMPLE_RATE)
        n_events_total += len(events)

        rel = wav.relative_to(args.audio_root)
        out_json = args.out_dir / rel.with_suffix(".breath.json")
        out_json.parent.mkdir(parents=True, exist_ok=True)

        payload = {
            "audio_file": str(wav),
            "sample_rate": SAMPLE_RATE,
            "duration_sec": len(signal) / SAMPLE_RATE,
            "labeler": "ruinskiy_lavner_2007_pseudo",
            "label_date": str(date.today()),
            "breath_events": [
                {
                    "start_sec": ev.start_sec,
                    "end_sec": ev.end_sec,
                    "confidence": "low",
                    "score": ev.score,
                }
                for ev in events
            ],
            "notes": f"Auto-generated by Ruinskiy baseline @ threshold={args.threshold}",
        }
        out_json.write_text(json.dumps(payload, indent=2))
        if i % 20 == 0 or i == len(wavs):
            print(f"  [{i}/{len(wavs)}] {wav.name} → {len(events)} events")

    print(f"\nDone. {n_events_total} pseudo-events across {len(wavs)} files.")
    print(f"Sidecars under: {args.out_dir}")


if __name__ == "__main__":
    main()
